export type ComponentCategory =
  | 'Layout'
  | 'Forms'
  | 'Feedback'
  | 'Data display'
  | 'Lab widgets'
  | 'Workflow'

export interface ComponentDoc {
  name: string
  category: ComponentCategory
  description: string
  example?: string
  related?: Array<{ text: string; link: string }>
}

const groups: Record<ComponentCategory, string[]> = {
  Layout: [
    'PluginWorkspaceView',
    'AppLayout',
    'AppContainer',
    'AppTopBar',
    'AppSidebar',
    'AppAvatarMenu',
    'AppPluginSwitcher',
    'PluginIcon',
    'Breadcrumb',
    'Divider',
    'FitPanel',
    'ResourceCard',
    'CollapsibleCard',
  ],
  Forms: [
    'BaseButton',
    'BaseInput',
    'BaseTextarea',
    'BaseSelect',
    'BaseCheckbox',
    'BaseToggle',
    'BaseRadioGroup',
    'BaseSlider',
    'ColorSlider',
    'BaseTabs',
    'SegmentedControl',
    'MultiSelect',
    'DropdownButton',
    'FormField',
    'DatePicker',
    'TimePicker',
    'DateTimePicker',
    'TimeRangeInput',
    'Calendar',
    'TagsInput',
    'NumberInput',
    'FileUploader',
    'FormulaInput',
    'SequenceInput',
    'UnitInput',
    'ConcentrationInput',
  ],
  Feedback: [
    'AlertBox',
    'AppToastContainer',
    'IconButton',
    'ThemeToggle',
    'Skeleton',
    'LoadingSpinner',
    'StatusIndicator',
    'ProgressBar',
    'Avatar',
    'EmptyState',
    'Tooltip',
    'BaseModal',
    'ConfirmDialog',
    'SettingsModal',
  ],
  'Data display': [
    'DataFrame',
    'ChartContainer',
    'ScientificNumber',
    'ChemicalFormula',
    'SequenceProgressBar',
    'AuditTrail',
    'BatchProgressList',
    'ExperimentDataViewer',
    'ExperimentCodeBadge',
    'InstrumentAlertLog',
    'InstrumentStateBadge',
    'InstrumentStatusCard',
    'LcmsSequenceTable',
    'BasePill',
  ],
  'Lab widgets': [
    'WellPlate',
    'RackEditor',
    'SampleLegend',
    'PlateMapEditor',
    'ExperimentTimeline',
    'SampleSelector',
    'AutoGroupModal',
    'GroupAssigner',
    'MoleculeInput',
    'DoseCalculator',
    'ReagentEditor',
    'ReagentList',
    'SampleHierarchyTree',
    'ProtocolStepEditor',
  ],
  Workflow: [
    'ComponentBindingRenderer',
    'ControlWorkspaceView',
    'DoseDesignWorkspaceView',
    'BioTemplateRenderer',
    'BioTemplateExperimentWorkspaceView',
    'BioTemplatePackWorkspaceView',
    'BioTemplatePresetWorkspaceView',
    'StepWizard',
    'FormBuilder',
    'FormActions',
    'ScheduleCalendar',
    'ExperimentSelectorModal',
    'ExperimentPopover',
  ],
}

const descriptions: Record<string, string> = {
  AlertBox: 'Inline status, warning, error, and success messages for plugin screens.',
  AppContainer: 'Lightweight content shell for standalone plugin screens and routed views.',
  AppLayout: 'Lower-level application shell with topbar, sidebar, and content slots.',
  AppSidebar: 'Sectioned sidebar for plugin-specific navigation and grouped tools.',
  AppTopBar: 'Platform-style top bar for shells that need custom navigation chrome.',
  BaseButton: 'Tokenized action button with variants, sizes, loading, and disabled states.',
  BaseCheckbox: 'Single checkbox control for boolean plugin settings and form fields.',
  BaseInput: 'Themed text and numeric input with error, placeholder, and v-model support.',
  BaseModal: 'Standard modal dialog with controlled visibility and footer slots.',
  BasePill: 'Compact status label for tables, metadata, and small state indicators.',
  BaseSelect: 'Themed select control with option objects, placeholder, and v-model support.',
  BaseTextarea: 'Multi-line input for notes, descriptions, and longer user-entered text.',
  ChemicalFormula: 'Formula renderer with scientific typography and element-aware formatting.',
  ConfirmDialog: 'Pre-built confirm-or-cancel dialog for destructive or high-friction actions.',
  DataFrame: 'Searchable, sortable, selectable table for dense experiment and analysis results.',
  EmptyState: 'Empty-list and empty-view treatment with optional action affordance.',
  FileUploader: 'Drag-and-drop file picker with accept, size, multiple, and error handling.',
  FormBuilder: 'Schema-driven form renderer for experiment-design and plugin settings UIs.',
  FormField: 'Label, hint, error, and accessibility wrapper for form controls.',
  PluginWorkspaceView: 'Default plugin frontend shell generated by current MINT scaffolds.',
  StepWizard: 'Multi-step workflow container with progress, validation, and navigation slots.',
  Tooltip: 'Hover/focus tooltip with smart positioning for compact explanations.',
  WellPlate: 'Interactive 96- and 384-well plate map with heatmaps, selection, and editing hooks.',
}

const examples: Record<string, string> = {
  AlertBox: `<AlertBox type="warning" title="Review required">
  Three samples need QC approval before publishing.
</AlertBox>`,
  BaseButton: `<BaseButton variant="primary" :loading="saving" @click="save">
  Save
</BaseButton>`,
  BaseInput: `<FormField label="Panel name" :error="errors.name" field-id="panel-name">
  <template #default="{ describedBy }">
    <BaseInput v-model="name" :aria-describedby="describedBy" />
  </template>
</FormField>`,
  BaseModal: `<BaseModal v-model="showModal" title="Edit panel">
  <p>Modal body content.</p>
  <template #footer>
    <BaseButton variant="ghost" @click="showModal = false">Cancel</BaseButton>
    <BaseButton variant="primary" @click="save">Save</BaseButton>
  </template>
</BaseModal>`,
  ChemicalFormula: `<ChemicalFormula formula="C6H12O6" />`,
  ConfirmDialog: `<ConfirmDialog
  v-model="confirmingDelete"
  title="Delete panel?"
  message="This cannot be undone."
  variant="danger"
  confirm-label="Delete"
  @confirm="confirmDelete"
/>`,
  DataFrame: `<DataFrame
  :columns="columns"
  :data="rows"
  row-key="id"
  searchable
  sortable
  sticky-header
/>`,
  FileUploader: `<FileUploader
  accept=".csv,.xlsx"
  :max-size="100 * 1024 * 1024"
  multiple
  @upload="uploadFiles"
/>`,
  FormBuilder: `<FormBuilder :schema="designSchema" v-model="designData" />`,
  PluginWorkspaceView: `<PluginWorkspaceView
  title="My plugin"
  subtitle="Dashboard"
  :page-selector="pluginPageSelectorItems"
  current-page-selector-id="dashboard"
>
  <AppContainer scrollable>
    <router-view />
  </AppContainer>
</PluginWorkspaceView>`,
  StepWizard: `<StepWizard v-model="currentStep" :steps="steps">
  <template #step-basics>
    <!-- basic fields -->
  </template>
  <template #step-review>
    <!-- summary -->
  </template>
</StepWizard>`,
  WellPlate: `<WellPlate
  v-model="selectedWells"
  :format="384"
  :wells="wells"
  selection-mode="multiple"
  size="fill"
/>`,
}

const related: Record<string, ComponentDoc['related']> = {
  FormBuilder: [{ text: 'FormBuilder deep dive', link: '/sdk/frontend/form-builder' }],
  WellPlate: [{ text: 'WellPlate playground', link: '/sdk/components/well-plate' }],
  DataFrame: [{ text: 'Design plugin with tables', link: '/sdk/tutorials/design-plugin-with-tables' }],
  PluginWorkspaceView: [{ text: 'Adding a frontend', link: '/sdk/tutorials/adding-a-frontend' }],
}

export function componentSlug(name: string): string {
  return name
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1-$2')
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .toLowerCase()
}

function defaultDescription(name: string, category: ComponentCategory): string {
  return `${name} is a ${category.toLowerCase()} component exported by @morscherlab/mint-sdk for plugin frontends.`
}

export const componentDocs: ComponentDoc[] = Object.entries(groups).flatMap(([category, names]) =>
  names.map((name) => ({
    name,
    category: category as ComponentCategory,
    description: descriptions[name] ?? defaultDescription(name, category as ComponentCategory),
    example: examples[name],
    related: related[name],
  })),
)

export const componentCategories = Object.keys(groups) as ComponentCategory[]

export const componentSidebarGroups = componentCategories.map((category) => ({
  text: category,
  collapsed: true,
  items: groups[category].map((name) => ({
    text: name,
    link: `/sdk/components/${componentSlug(name)}`,
  })),
}))

export function getComponentDoc(name: string): ComponentDoc | undefined {
  return componentDocs.find((component) => component.name === name)
}
